from __future__ import annotations

from enum import Enum


class RejectionReason(str, Enum):
    SCHEMA_INVALID = "SCHEMA_INVALID"
    ID_MISMATCH = "ID_MISMATCH"
    RENDER_ROUNDTRIP_MISMATCH = "RENDER_ROUNDTRIP_MISMATCH"
    METADATA_EXTRA_NOT_ALLOWED = "METADATA_EXTRA_NOT_ALLOWED"
    TASK_MISMATCH = "TASK_MISMATCH"
    AXES_INCOMPLETE = "AXES_INCOMPLETE"

    SECRET_DETECTED = "SECRET_DETECTED"
    PII_UNRESOLVED = "PII_UNRESOLVED"
    SURROGATE_RESIDUE = "SURROGATE_RESIDUE"
    PRIVATE_FACT = "PRIVATE_FACT"
    CONSENT_UNCLEAR = "CONSENT_UNCLEAR"

    REVIEW_MISSING = "REVIEW_MISSING"
    REVIEW_SIGNATURE_MISMATCH = "REVIEW_SIGNATURE_MISMATCH"
    REVIEW_GATE_FAILED = "REVIEW_GATE_FAILED"
    REVIEW_SCORE_BELOW_THRESHOLD = "REVIEW_SCORE_BELOW_THRESHOLD"
    OPERATOR_REJECTED = "OPERATOR_REJECTED"
    INCORRECT_BEHAVIOR = "INCORRECT_BEHAVIOR"
    BAD_POLICY = "BAD_POLICY"

    CORPUS_DUPLICATE = "CORPUS_DUPLICATE"
    NEAR_DUPLICATE = "NEAR_DUPLICATE"
    EVAL_LEAKAGE = "EVAL_LEAKAGE"
    LOW_INFORMATION = "LOW_INFORMATION"
    INSUFFICIENT_VARIATION = "INSUFFICIENT_VARIATION"
    UNRESOLVED_AMBIGUITY = "UNRESOLVED_AMBIGUITY"

    PROVENANCE_INVALID = "PROVENANCE_INVALID"
    LANE_NOT_PROMOTABLE = "LANE_NOT_PROMOTABLE"
    STAGING_INTEGRITY = "STAGING_INTEGRITY"


PRIVACY_REASONS: frozenset[RejectionReason] = frozenset(
    {
        RejectionReason.SECRET_DETECTED,
        RejectionReason.PII_UNRESOLVED,
        RejectionReason.SURROGATE_RESIDUE,
        RejectionReason.PRIVATE_FACT,
        RejectionReason.CONSENT_UNCLEAR,
    }
)

RETRYABLE_REASONS: frozenset[RejectionReason] = frozenset(
    {
        RejectionReason.SCHEMA_INVALID,
        RejectionReason.AXES_INCOMPLETE,
        RejectionReason.PII_UNRESOLVED,
        RejectionReason.PRIVATE_FACT,
        RejectionReason.REVIEW_SCORE_BELOW_THRESHOLD,
        RejectionReason.INCORRECT_BEHAVIOR,
        RejectionReason.UNRESOLVED_AMBIGUITY,
        RejectionReason.METADATA_EXTRA_NOT_ALLOWED,
    }
)
